name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm install
      
      - name: Setup Nx SHAs
        uses: nrwl/nx-set-shas@v4
      
      - name: Lint affected
        run: pnpm nx affected -t lint --parallel=3
      
      - name: Test affected
        run: pnpm nx affected -t test --parallel=3 --coverage
      
      - name: Build affected
        run: pnpm nx affected -t build --parallel=3

  security:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
      
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm install
      
      - name: Security audit
        run: pnpm audit
      
      - name: Check for secrets
        run: |
          if grep -r "sk-" . --include="*.ts" --include="*.js" --include="*.json" --exclude-dir=node_modules; then
            echo "Potential API key found!"
            exit 1
          fi