name: Deploy to Cloudflare

on:
  push:
    branches: [main]
    paths:
      - 'apps/playground/**'
  workflow_dispatch:

env:
  NODE_VERSION: '20'
  PNPM_VERSION: '9.15.0'

jobs:
  check-friday:
    name: Friday Afternoon Check
    runs-on: ubuntu-latest
    outputs:
      should-deploy: ${{ steps.check.outputs.should-deploy }}
    steps:
      - name: Check deployment time
        id: check
        run: |
          current_hour=$(date -u +%H)
          current_day=$(date -u +%u)
          
          # Friday is day 5, and 15:00 UTC is 3pm
          if [ "$current_day" = "5" ] && [ "$current_hour" -ge "15" ]; then
            echo "should-deploy=false" >> $GITHUB_OUTPUT
            echo "::warning::Friday afternoon deployment blocked for safety"
          else
            echo "should-deploy=true" >> $GITHUB_OUTPUT
          fi

  deploy-playground:
    name: Deploy Playground to Cloudflare Workers
    runs-on: ubuntu-latest
    needs: check-friday
    if: needs.check-friday.outputs.should-deploy == 'true'
    environment:
      name: production
      url: ${{ steps.deploy.outputs.url }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.0
        env:
          PNPM_REGISTRY: https://registry.npmmirror.com

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build playground
        run: pnpm nx build playground

      - name: Deploy to Cloudflare Workers
        id: deploy
        run: |
          cd apps/playground
          echo "Deploying playground to Cloudflare Workers..."
          pnpm wrangler deploy --compatibility-date 2024-08-26
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Create deployment audit log
        if: always()
        run: |
          mkdir -p .github/audit
          cat > .github/audit/deployment-$(date +%Y%m%d-%H%M%S).md << EOF
          # Deployment Audit Log - $(date -u +"%Y-%m-%d %H:%M:%S UTC")
          
          ## Deployment Details
          - **Project**: playground
          - **Target**: Cloudflare Workers
          - **Commit**: ${{ github.sha }}
          - **Actor**: ${{ github.actor }}
          - **Status**: ${{ job.status }}
          
          ## Security Checks
          - Friday afternoon check: ${{ needs.check-friday.outputs.should-deploy }}
          - Deployment time: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
          
          ## Environment
          - Node.js: ${{ env.NODE_VERSION }}
          - pnpm: ${{ env.PNPM_VERSION }}
          EOF

      - name: Commit audit log
        if: success()
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .github/audit/
          git commit -m "ci: Add deployment audit log for ${{ github.sha }}" || exit 0
          git push

  deploy-blocked:
    name: Deployment Blocked
    runs-on: ubuntu-latest
    needs: check-friday
    if: needs.check-friday.outputs.should-deploy == 'false'
    
    steps:
      - name: Friday afternoon deployment blocked
        run: |
          echo "::error::Deployment blocked - Friday afternoon safety restriction active"
          echo "Deployments are automatically blocked on Fridays after 3 PM UTC for safety."
          echo "Please deploy on Monday or earlier in the week."
          exit 1